### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by soldair** [simenkid/lua-events#1]
it would be really great to use this code properly versioned with semver and published to npm.

Its totally ok to publish lua to npm. you can choose a prefix like nodemcu or lua like you did with your repos.

The nice thing is this would allow us to write tools for flattening the dependencies and minifiying them for upload in a shareable consistent way.

i notice that you don't have git tags for the 1.0.0 release and pulling from master makes me a bit nervous. 

I'm working with my esp and nodemcu-lua and it seems like you are publishing exactly the modules i felt like i needed nodemcu-timer etc. and i really want to contribute!

like there is a missing http-server im working on and net connections can only queue one send before waiting for "sent" so i want to wrap this in a module as well.
But first i'm working on a tap module for testing on board. Using [nodemcu-tool](https://github.com/AndiDittrich/NodeMCU-Tool) to upload my test files, some node for servers and test results validation.

thank you!

**Comment by simenkid** [comment]
I didn't even notice that I can use npm to manage my lua things. Thanks!!

I've tagged the _nodemcu-timer_ and _lua-events_ for their v1.0.0 release respectively, and published them to npm with names _nodemcu-timer_ and _lua-eventemitter_.

I am using these two modules on my IoT machines, and I found that the memory is tight on ESP8266. Schedule too many things or register too many event handlers will raise a "not enough memory" problem. I hope this reminder may help.

I'm trying to simplify them to further lower down their memory usage, because the "not enough memory" problem bothers me as well. 

Please let me know if there are any problems.

**Comment by soldair** [comment]
great! thank you
